spring.application.name=springbootproject1

spring.datasource.url=jdbc:mysql://localhost:3306/web1
spring.datasource.username=root
spring.datasource.password=742903

mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 需要在pom引入spring-boot-configuration-processor，还有配置绑定类configuration/UploadConfiguration.java和UploadController.java
# 要使照片上传独立在项目外
# spring内置的tomcat对照片大小有限制
application.upload-root=D:\\Project\\upload
# 配置静态资源映射，让上传的文件可以通过HTTP访问
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/static/,classpath:/public/,classpath:/resources/,file:${application.upload-root}

# 上传大小限制（解决 413 Payload Too Large）
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
